# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Python image from the Docker Hub
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the pyproject.toml and other necessary files
COPY pyproject.toml /app/

# Install build backend
RUN pip install --no-cache-dir hatchling

# Install the dependencies
RUN pip install --no-cache-dir fastmcp gitpython uvicorn

# Copy the rest of the working directory contents into the container
COPY src /app/src

# Expose port for uvicorn
EXPOSE 8000

# Run the application
CMD ["uvicorn", "mcp_git_ingest.main:mcp.run", "--host", "0.0.0.0", "--port", "8000"]